### PR TITLE
Fix Mu Character.

### PR DESCRIPTION
**Pull request by ilan-gold**
The mu character appeared to somewhat non-functioning previously.  I'm not 100% sure what is going on here but the character now prints as &#956; instead of &#181; which seems more correct.  @LauraKuett could you test this out to confirm?

### CODE REVIEW

**Comment by ilan-gold** [comment]
I am at a bit of a loss here @LauraKuett - it should be possible to get a greek character to print but I'm having trouble.  Will keep hammering away.

**Comment by ilan-gold** [comment]
@LauraKuett and @jwindhager I opened an issue on image.sc about this: https://forum.image.sc/t/micro-character-in-omexml-from-python/53578/4

**Comment by jwindhager** [comment]
Hi Ilan, thanks so much for digging and your report on image.sc. Seems like an encoding issue indeed. I remember switching from UTF-8 to ASCII because of #4 reported by our software engineer. But from what @cgohlke wrote on image.sc, the warning about non-ASCII seems to be a bug in tifffile and the OME-XML should be UTF-8. I'll double-check over the weekend and update xtiff as soon as there is a fix available for tifffile (if that's the case).

**Comment by jwindhager** [comment]
xtiff 0.7.6 now writes OME-XML as UTF-8 again (technically not supported by TIFF, but required by OME-XML/the microns character). tifffile's ASCII encoding (and associated error message - not a bug, apologies for not reading the thread on image.sc properly!) is skipped by passing the encoded byte string to tifffile. Please let me know if that works for you @ilan-gold. Thanks again for digging @ilan-gold and for the tifffile support @cgohlke!

**Pull request closed without merging**
